name: Run tests

on:
  push:
    branches: [main]
    
jobs:
  cypress-run:
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout
         uses: actions/checkout@v1
       - name: Install server dependencies
         uses: bahmutov/npm-install@v1
         with:
           working-directory: server
       - name: Install web dependencies
         uses: bahmutov/npm-install@v1
         with:
           working-directory: web
       - name: Run all tests
         uses: cypress-io/github-action@v2
         with:
           working-directory: web
           install: false
           start: npm run start:ci
           wait-on: 'http://localhost:3000'
